# Generated by Django 4.2 on 2023-04-28 11:19

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_gamepricemodel_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepricemodel',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название магазина'),
        ),
        migrations.AlterField(
            model_name='gamepricemodel',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=10, verbose_name='Цена'),
        ),
    ]
