# Generated by Django 4.2 on 2023-04-28 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_platform', '0002_gameplatformmodel_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplatformmodel',
            name='game',
        ),
    ]
