# Generated by Django 4.2 on 2023-04-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_platform', '0003_remove_gameplatformmodel_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplatformmodel',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание платформы'),
        ),
        migrations.AlterField(
            model_name='gameplatformmodel',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название платформы'),
        ),
    ]
