# Generated by Django 4.2 on 2023-04-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0003_remove_gamegenremodel_game'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='genres',
            field=models.ManyToManyField(to='genre.gamegenremodel'),
        ),
    ]
