# Generated by Django 4.2 on 2023-04-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_platform', '0003_remove_gameplatformmodel_game'),
        ('game', '0002_gamemodel_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='game_platform',
            field=models.ManyToManyField(to='game_platform.gameplatformmodel'),
        ),
    ]
