# Generated by Django 4.2 on 2023-04-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0004_alter_gamegenremodel_name'),
        ('game_platform', '0003_remove_gameplatformmodel_game'),
        ('game', '0004_alter_gamemodel_game_platform_alter_gamemodel_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='game_platform',
            field=models.ManyToManyField(blank=True, to='game_platform.gameplatformmodel'),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='genres',
            field=models.ManyToManyField(blank=True, to='genre.gamegenremodel'),
        ),
    ]
