# Generated by Django 4.2 on 2023-04-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamegenremodel',
            name='game',
            field=models.ManyToManyField(to='game.gamemodel'),
        ),
    ]
