# Generated by Django 4.2 on 2023-04-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_gamegenremodel_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamegenremodel',
            name='game',
        ),
    ]
